### ISSUE TITLE
`accInputHash` discrepancies on mainnet and cardona

### ISSUE THREAD

**Issue by leovct** [0xPolygon/cdk-erigon#1288]
## Description

I’ve worked on a sanity check script for kurtosis-cdk to identify discrepancies between RPCs, datastreamer, and L1 contracts. Upon running this script against both testnet and mainnet, I came across a few interesting observations:

### 1. `accInputHash` discrepancies on Mainnet

On Mainnet, I discovered inconsistencies in the `accInputHash` field across our different RPCs. I’m not sure if it’s critical though... Interestingly, PolygonScan sometimes reports a different value for this field compared to our RPCs. For instance, in the case of batch `2129865` which has been created over 25 hours ago and has been verified for quite some time. See the first screenshot attached. Unfortunately, this issue is not isolated; I have observed similar inconsistencies across numerous batches.

<img width="1062" alt="mainnet-accinputhash-mismatch" src="https://github.com/user-attachments/assets/ad73f2d6-b761-4855-ac87-9db4b6c9a711">

### 2. `accInputHash` discrepancies on Cardona

Additionally, I found comparable discrepancies on Cardona, where the `accInputHash` field also shows inconsistencies between our RPCs and the values displayed on PolygonScan. See the second screenshot attached.

<img width="1050" alt="cardona-accinputhash-mismatch" src="https://github.com/user-attachments/assets/4af05e19-bced-4666-9c25-58ceb45a7828">

## References

- [fetch rpc data
](https://gist.github.com/leovct/ea75e040b07375430fbb7ee195bceef7)
- [fetch polygonscan data](https://gist.github.com/leovct/b986d40cdeacbf782ea3a73db442bf21)

**Comment by V-Staykov** [comment]
I just made some tests and seems our latest version returnes correct accinputhash for all cardona and mainnet batch numbers. The difference is probably because of different node versions and the polygonscan being hooked up to an older node version. Either that, or it generated the data it shows on older version and now needs to resync.

**Comment by leovct** [comment]
> I just made some tests and seems our latest version returnes correct accinputhash for all cardona and mainnet batch numbers. The difference is probably because of different node versions and the polygonscan being hooked up to an older node version. Either that, or it generated the data it shows on older version and now needs to resync.

Ok that makes sense, I just queried the last 5 verified batches on both cardona and mainnet and could find some inconsistencies but I'm not sure if these endpoints are up to date. Not sure if the components have been updated since I reported the issue though. The other RPC endpoints seem in sync.

## Mainnet

Last verified batch on mainnet: 2131097
Found an `accInputHash` mismatch on batch 2131095

<img width="753" alt="Screenshot 2024-10-15 at 12 15 03" src="https://github.com/user-attachments/assets/4de80309-be42-458b-ade8-3ed6768276f0">

## Cardona

Last verified batch on cardona: 128588
Found an `accInputHash` mismatch on batch 128588 (but also 128586)

<img width="651" alt="Screenshot 2024-10-15 at 12 17 29" src="https://github.com/user-attachments/assets/63ef7759-a6cf-44c7-bf75-c5f2e8d879ab">

**Comment by Sharonbc01** [comment]
@V-Staykov please check endpoints are valid.

**Comment by V-Staykov** [comment]
I tested the mentioned batches and they now seem to match on the cardona rpc and ws endpoints. I then tried to ge tthe last verified batch and redo the test with it and they mismatch. So there seems to be a problem when getting the batch data for the latest verified batch.

**Comment by Sharonbc01** [comment]
FYI @hexoscott

**Comment by V-Staykov** [comment]
So far I can't reproduce it locally but it might be fixed in some of the latest commits. I am checking for beta27 right now.

**Comment by V-Staykov** [comment]
I can't reproduce this in any way locally for some reason. Also looking ad the code I can't find a reason for the result to differ in time.

**Comment by leovct** [comment]
I ran a few tests today. All the endpoints look fine for me except https://rpc.cardona.zkevm-rpc.com/. For example, when I did the check on Cardona, 129658 was the latest verified batch. I queried the batch just before, 129657, and the RPC gives me two different responses for `accInputHash`.

At 16:25:38, it returns `"accInputHash": "0xec7078c0b811f31246312b17065f4d7e51455d898f7079f787efcefc0cb5a5b9"`.

<img width="1709" alt="Screenshot 2024-11-05 at 16 26 45" src="https://github.com/user-attachments/assets/e2c7a897-fb19-4f28-bc69-0c83d60ca79a">

While at 16:26:18, it returns `"accInputHash": "0x8062e6a00b0c51cb25718ac08e266bf04d945aa036b07e427d06c6c9814a08a7"`.

<img width="1712" alt="Screenshot 2024-11-05 at 16 26 52" src="https://github.com/user-attachments/assets/e8cc948d-3765-4d5d-bd2e-b8642d3ad457">

**Comment by hexoscott** [comment]
There are flaws in the older versions of cdk-erigon.  Beta7 has been cut now which will address those, once that version has reached Bali / Cardona we can open up testing of this again.

**Comment by Sharonbc01** [comment]
Hi @leovct please can you test this now on Bali if possible as we have deployed [v2.60.0-beta8](https://github.com/0xPolygonHermez/cdk-erigon/releases/tag/v2.60.0-beta8) on Bali now.

cc: @praetoriansentry

**Comment by leovct** [comment]
> Hi @leovct please can you test this now on Bali if possible as we have deployed [v2.60.0-beta8](https://github.com/0xPolygonHermez/cdk-erigon/releases/tag/v2.60.0-beta8) on Bali now.
> 
> cc: @praetoriansentry

Hi @Sharonbc01, I did a small test today against Bali and Cardona.

For Bali, I don't see any diff between the internal and debug RPC. It looks good to me! 🎉

For Cardona, I still see some weird behaviours with the third RPC endpoint: https://rpc.cardona.zkevm-rpc.com/. When queried multiple times, it return different results for the `accInputHash` field. All the other endpoints seem fine.

# 14/11/2024

For this test, I queried [130951](https://cardona-zkevm.polygonscan.com/batch/130951) batch data from the different endpoints. This batch has been finalized a while ago, at 05:51:02 today. The same thing happens for other verified batch such as [130952](https://cardona-zkevm.polygonscan.com/batch/130952), [130950](https://cardona-zkevm.polygonscan.com/batch/130950), [130949](https://cardona-zkevm.polygonscan.com/batch/130949), etc... It looks like the `accInputHash` field is re-computed every time and the result is not deterministic.

First query at 09:14:07: all the endpoints return the same result.

<details>
<summary>Click to expand</summary>

```bash
$ ./fetch_rpc_data.sh cardona 130951
Endpoint: https://rpc-debug.cardona.zkevm-rpc.com/
{
  "accInputHash": "0xfd5141b2892e3b8ac99427a3fa89e940af87072c58e2deaf70c88b9086ccb7ce",
  "blocks": 574,
  "closed": true,
  "coinbase": "0x761d53b47334bee6612c0bd1467fb881435375b2",
  "globalExitRoot": "0x8153fb885ba5ccef9063af371c0803318d56ba65192387f9c8a9aca8373809ff",
  "localExitRoot": "0xdcdcff63a1d2d64154e2f480d804131b2c399e04a850f70e36b48b39608a22c0",
  "mainnetExitRoot": "0x6ce23142c0a224657d8a53ce226308864c096d55694eca00bd9c3b3e472a3b42",
  "number": "0x1ff87",
  "rollupExitRoot": "0x1701a28ea10b5b1e7a62f60e857addc01653b5ccde773e77af1554805eda21da",
  "sendSequencesTxHash": "0x49018954cd5f94086b455917cb976f992cc8cda337672a82d058d0909d075db8",
  "stateRoot": "0xb2dbc1890279a290c244b86a24eaeef48044e05df7f66c0e858c24052042a856",
  "timestamp": "0x673596c5",
  "transactions": 73,
  "verifyBatchTxHash": "0xa1b73bc1e9f4d290ca29e5d0cce2cba4573fe109abeb48b53f5bfe1f17ab1f81"
}

Endpoint: https://etherscan.cardona.zkevm-rpc.com/
{
  "accInputHash": "0xfd5141b2892e3b8ac99427a3fa89e940af87072c58e2deaf70c88b9086ccb7ce",
  "blocks": 574,
  "closed": true,
  "coinbase": "0x761d53b47334bee6612c0bd1467fb881435375b2",
  "globalExitRoot": "0x8153fb885ba5ccef9063af371c0803318d56ba65192387f9c8a9aca8373809ff",
  "localExitRoot": "0xdcdcff63a1d2d64154e2f480d804131b2c399e04a850f70e36b48b39608a22c0",
  "mainnetExitRoot": "0x6ce23142c0a224657d8a53ce226308864c096d55694eca00bd9c3b3e472a3b42",
  "number": "0x1ff87",
  "rollupExitRoot": "0x1701a28ea10b5b1e7a62f60e857addc01653b5ccde773e77af1554805eda21da",
  "sendSequencesTxHash": "0x49018954cd5f94086b455917cb976f992cc8cda337672a82d058d0909d075db8",
  "stateRoot": "0xb2dbc1890279a290c244b86a24eaeef48044e05df7f66c0e858c24052042a856",
  "timestamp": "0x673596c5",
  "transactions": 73,
  "verifyBatchTxHash": "0xa1b73bc1e9f4d290ca29e5d0cce2cba4573fe109abeb48b53f5bfe1f17ab1f81"
}

Endpoint: https://rpc.cardona.zkevm-rpc.com/
{
  "accInputHash": "0xfd5141b2892e3b8ac99427a3fa89e940af87072c58e2deaf70c88b9086ccb7ce",
  "blocks": 574,
  "closed": true,
  "coinbase": "0x761d53b47334bee6612c0bd1467fb881435375b2",
  "globalExitRoot": "0x8153fb885ba5ccef9063af371c0803318d56ba65192387f9c8a9aca8373809ff",
  "localExitRoot": "0xdcdcff63a1d2d64154e2f480d804131b2c399e04a850f70e36b48b39608a22c0",
  "mainnetExitRoot": "0x6ce23142c0a224657d8a53ce226308864c096d55694eca00bd9c3b3e472a3b42",
  "number": "0x1ff87",
  "rollupExitRoot": "0x1701a28ea10b5b1e7a62f60e857addc01653b5ccde773e77af1554805eda21da",
  "sendSequencesTxHash": "0x49018954cd5f94086b455917cb976f992cc8cda337672a82d058d0909d075db8",
  "stateRoot": "0xb2dbc1890279a290c244b86a24eaeef48044e05df7f66c0e858c24052042a856",
  "timestamp": "0x673596c5",
  "transactions": 73,
  "verifyBatchTxHash": "0xa1b73bc1e9f4d290ca29e5d0cce2cba4573fe109abeb48b53f5bfe1f17ab1f81"
}

Endpoint: https://ws.cardona.zkevm-rpc.com/
{
  "accInputHash": "0xfd5141b2892e3b8ac99427a3fa89e940af87072c58e2deaf70c88b9086ccb7ce",
  "blocks": 574,
  "closed": true,
  "coinbase": "0x761d53b47334bee6612c0bd1467fb881435375b2",
  "globalExitRoot": "0x8153fb885ba5ccef9063af371c0803318d56ba65192387f9c8a9aca8373809ff",
  "localExitRoot": "0xdcdcff63a1d2d64154e2f480d804131b2c399e04a850f70e36b48b39608a22c0",
  "mainnetExitRoot": "0x6ce23142c0a224657d8a53ce226308864c096d55694eca00bd9c3b3e472a3b42",
  "number": "0x1ff87",
  "rollupExitRoot": "0x1701a28ea10b5b1e7a62f60e857addc01653b5ccde773e77af1554805eda21da",
  "sendSequencesTxHash": "0x49018954cd5f94086b455917cb976f992cc8cda337672a82d058d0909d075db8",
  "stateRoot": "0xb2dbc1890279a290c244b86a24eaeef48044e05df7f66c0e858c24052042a856",
  "timestamp": "0x673596c5",
  "transactions": 73,
  "verifyBatchTxHash": "0xa1b73bc1e9f4d290ca29e5d0cce2cba4573fe109abeb48b53f5bfe1f17ab1f81"
}

JSON files saved at /var/folders/7m/3_x4ns7557x52hb6vncqkx8h0000gn/T/tmp.hZygttIPgN
Comparing cardona_130951_1.json and cardona_130951_2.json:
✅ No diff

Comparing cardona_130951_1.json and cardona_130951_3.json:
✅ No diff

Comparing cardona_130951_1.json and cardona_130951_4.json:
✅ No diff

Comparing cardona_130951_2.json and cardona_130951_3.json:
✅ No diff

Comparing cardona_130951_2.json and cardona_130951_4.json:
✅ No diff

Comparing cardona_130951_3.json and cardona_130951_4.json:
✅ No diff
```

</details>
<br/>

Second query at 09:14:10: all the endpoints return the same result once again.

<details>
<summary>Click to expand</summary>

```bash
$ ./fetch_rpc_data.sh cardona 130951
Endpoint: https://rpc-debug.cardona.zkevm-rpc.com/
{
  "accInputHash": "0xfd5141b2892e3b8ac99427a3fa89e940af87072c58e2deaf70c88b9086ccb7ce",
  "blocks": 574,
  "closed": true,
  "coinbase": "0x761d53b47334bee6612c0bd1467fb881435375b2",
  "globalExitRoot": "0x8153fb885ba5ccef9063af371c0803318d56ba65192387f9c8a9aca8373809ff",
  "localExitRoot": "0xdcdcff63a1d2d64154e2f480d804131b2c399e04a850f70e36b48b39608a22c0",
  "mainnetExitRoot": "0x6ce23142c0a224657d8a53ce226308864c096d55694eca00bd9c3b3e472a3b42",
  "number": "0x1ff87",
  "rollupExitRoot": "0x1701a28ea10b5b1e7a62f60e857addc01653b5ccde773e77af1554805eda21da",
  "sendSequencesTxHash": "0x49018954cd5f94086b455917cb976f992cc8cda337672a82d058d0909d075db8",
  "stateRoot": "0xb2dbc1890279a290c244b86a24eaeef48044e05df7f66c0e858c24052042a856",
  "timestamp": "0x673596c5",
  "transactions": 73,
  "verifyBatchTxHash": "0xa1b73bc1e9f4d290ca29e5d0cce2cba4573fe109abeb48b53f5bfe1f17ab1f81"
}

Endpoint: https://etherscan.cardona.zkevm-rpc.com/
{
  "accInputHash": "0xfd5141b2892e3b8ac99427a3fa89e940af87072c58e2deaf70c88b9086ccb7ce",
  "blocks": 574,
  "closed": true,
  "coinbase": "0x761d53b47334bee6612c0bd1467fb881435375b2",
  "globalExitRoot": "0x8153fb885ba5ccef9063af371c0803318d56ba65192387f9c8a9aca8373809ff",
  "localExitRoot": "0xdcdcff63a1d2d64154e2f480d804131b2c399e04a850f70e36b48b39608a22c0",
  "mainnetExitRoot": "0x6ce23142c0a224657d8a53ce226308864c096d55694eca00bd9c3b3e472a3b42",
  "number": "0x1ff87",
  "rollupExitRoot": "0x1701a28ea10b5b1e7a62f60e857addc01653b5ccde773e77af1554805eda21da",
  "sendSequencesTxHash": "0x49018954cd5f94086b455917cb976f992cc8cda337672a82d058d0909d075db8",
  "stateRoot": "0xb2dbc1890279a290c244b86a24eaeef48044e05df7f66c0e858c24052042a856",
  "timestamp": "0x673596c5",
  "transactions": 73,
  "verifyBatchTxHash": "0xa1b73bc1e9f4d290ca29e5d0cce2cba4573fe109abeb48b53f5bfe1f17ab1f81"
}

Endpoint: https://rpc.cardona.zkevm-rpc.com/
{
  "accInputHash": "0xfd5141b2892e3b8ac99427a3fa89e940af87072c58e2deaf70c88b9086ccb7ce",
  "blocks": 574,
  "closed": true,
  "coinbase": "0x761d53b47334bee6612c0bd1467fb881435375b2",
  "globalExitRoot": "0x8153fb885ba5ccef9063af371c0803318d56ba65192387f9c8a9aca8373809ff",
  "localExitRoot": "0xdcdcff63a1d2d64154e2f480d804131b2c399e04a850f70e36b48b39608a22c0",
  "mainnetExitRoot": "0x6ce23142c0a224657d8a53ce226308864c096d55694eca00bd9c3b3e472a3b42",
  "number": "0x1ff87",
  "rollupExitRoot": "0x1701a28ea10b5b1e7a62f60e857addc01653b5ccde773e77af1554805eda21da",
  "sendSequencesTxHash": "0x49018954cd5f94086b455917cb976f992cc8cda337672a82d058d0909d075db8",
  "stateRoot": "0xb2dbc1890279a290c244b86a24eaeef48044e05df7f66c0e858c24052042a856",
  "timestamp": "0x673596c5",
  "transactions": 73,
  "verifyBatchTxHash": "0xa1b73bc1e9f4d290ca29e5d0cce2cba4573fe109abeb48b53f5bfe1f17ab1f81"
}

Endpoint: https://ws.cardona.zkevm-rpc.com/
{
  "accInputHash": "0xfd5141b2892e3b8ac99427a3fa89e940af87072c58e2deaf70c88b9086ccb7ce",
  "blocks": 574,
  "closed": true,
  "coinbase": "0x761d53b47334bee6612c0bd1467fb881435375b2",
  "globalExitRoot": "0x8153fb885ba5ccef9063af371c0803318d56ba65192387f9c8a9aca8373809ff",
  "localExitRoot": "0xdcdcff63a1d2d64154e2f480d804131b2c399e04a850f70e36b48b39608a22c0",
  "mainnetExitRoot": "0x6ce23142c0a224657d8a53ce226308864c096d55694eca00bd9c3b3e472a3b42",
  "number": "0x1ff87",
  "rollupExitRoot": "0x1701a28ea10b5b1e7a62f60e857addc01653b5ccde773e77af1554805eda21da",
  "sendSequencesTxHash": "0x49018954cd5f94086b455917cb976f992cc8cda337672a82d058d0909d075db8",
  "stateRoot": "0xb2dbc1890279a290c244b86a24eaeef48044e05df7f66c0e858c24052042a856",
  "timestamp": "0x673596c5",
  "transactions": 73,
  "verifyBatchTxHash": "0xa1b73bc1e9f4d290ca29e5d0cce2cba4573fe109abeb48b53f5bfe1f17ab1f81"
}

JSON files saved at /var/folders/7m/3_x4ns7557x52hb6vncqkx8h0000gn/T/tmp.9UewXaJUng
Comparing cardona_130951_1.json and cardona_130951_2.json:
✅ No diff

Comparing cardona_130951_1.json and cardona_130951_3.json:
✅ No diff

Comparing cardona_130951_1.json and cardona_130951_4.json:
✅ No diff

Comparing cardona_130951_2.json and cardona_130951_3.json:
✅ No diff

Comparing cardona_130951_2.json and cardona_130951_4.json:
✅ No diff

Comparing cardona_130951_3.json and cardona_130951_4.json:
✅ No diff
```
</details>
<br/>

Third query at 09:14:25: the third endpoint (https://rpc.cardona.zkevm-rpc.com/) returns a different `accInputHash` value.

<details>
<summary>Click to expand</summary>

```bash
$ ./fetch_rpc_data.sh cardona 130951
Endpoint: https://rpc-debug.cardona.zkevm-rpc.com/
{
  "accInputHash": "0xfd5141b2892e3b8ac99427a3fa89e940af87072c58e2deaf70c88b9086ccb7ce",
  "blocks": 574,
  "closed": true,
  "coinbase": "0x761d53b47334bee6612c0bd1467fb881435375b2",
  "globalExitRoot": "0x8153fb885ba5ccef9063af371c0803318d56ba65192387f9c8a9aca8373809ff",
  "localExitRoot": "0xdcdcff63a1d2d64154e2f480d804131b2c399e04a850f70e36b48b39608a22c0",
  "mainnetExitRoot": "0x6ce23142c0a224657d8a53ce226308864c096d55694eca00bd9c3b3e472a3b42",
  "number": "0x1ff87",
  "rollupExitRoot": "0x1701a28ea10b5b1e7a62f60e857addc01653b5ccde773e77af1554805eda21da",
  "sendSequencesTxHash": "0x49018954cd5f94086b455917cb976f992cc8cda337672a82d058d0909d075db8",
  "stateRoot": "0xb2dbc1890279a290c244b86a24eaeef48044e05df7f66c0e858c24052042a856",
  "timestamp": "0x673596c5",
  "transactions": 73,
  "verifyBatchTxHash": "0xa1b73bc1e9f4d290ca29e5d0cce2cba4573fe109abeb48b53f5bfe1f17ab1f81"
}

Endpoint: https://etherscan.cardona.zkevm-rpc.com/
{
  "accInputHash": "0xfd5141b2892e3b8ac99427a3fa89e940af87072c58e2deaf70c88b9086ccb7ce",
  "blocks": 574,
  "closed": true,
  "coinbase": "0x761d53b47334bee6612c0bd1467fb881435375b2",
  "globalExitRoot": "0x8153fb885ba5ccef9063af371c0803318d56ba65192387f9c8a9aca8373809ff",
  "localExitRoot": "0xdcdcff63a1d2d64154e2f480d804131b2c399e04a850f70e36b48b39608a22c0",
  "mainnetExitRoot": "0x6ce23142c0a224657d8a53ce226308864c096d55694eca00bd9c3b3e472a3b42",
  "number": "0x1ff87",
  "rollupExitRoot": "0x1701a28ea10b5b1e7a62f60e857addc01653b5ccde773e77af1554805eda21da",
  "sendSequencesTxHash": "0x49018954cd5f94086b455917cb976f992cc8cda337672a82d058d0909d075db8",
  "stateRoot": "0xb2dbc1890279a290c244b86a24eaeef48044e05df7f66c0e858c24052042a856",
  "timestamp": "0x673596c5",
  "transactions": 73,
  "verifyBatchTxHash": "0xa1b73bc1e9f4d290ca29e5d0cce2cba4573fe109abeb48b53f5bfe1f17ab1f81"
}

Endpoint: https://rpc.cardona.zkevm-rpc.com/
{
  "accInputHash": "0x86c9ccbb52dc881fc344f36165972228958a33c2bbaa04a6dbbf71bc8bbfae76",
  "blocks": 574,
  "closed": true,
  "coinbase": "0x761d53b47334bee6612c0bd1467fb881435375b2",
  "globalExitRoot": "0x8153fb885ba5ccef9063af371c0803318d56ba65192387f9c8a9aca8373809ff",
  "localExitRoot": "0xdcdcff63a1d2d64154e2f480d804131b2c399e04a850f70e36b48b39608a22c0",
  "mainnetExitRoot": "0x6ce23142c0a224657d8a53ce226308864c096d55694eca00bd9c3b3e472a3b42",
  "number": "0x1ff87",
  "rollupExitRoot": "0x1701a28ea10b5b1e7a62f60e857addc01653b5ccde773e77af1554805eda21da",
  "sendSequencesTxHash": "0x49018954cd5f94086b455917cb976f992cc8cda337672a82d058d0909d075db8",
  "stateRoot": "0xb2dbc1890279a290c244b86a24eaeef48044e05df7f66c0e858c24052042a856",
  "timestamp": "0x673596c5",
  "transactions": 73,
  "verifyBatchTxHash": "0xa1b73bc1e9f4d290ca29e5d0cce2cba4573fe109abeb48b53f5bfe1f17ab1f81"
}

Endpoint: https://ws.cardona.zkevm-rpc.com/
{
  "accInputHash": "0xfd5141b2892e3b8ac99427a3fa89e940af87072c58e2deaf70c88b9086ccb7ce",
  "blocks": 574,
  "closed": true,
  "coinbase": "0x761d53b47334bee6612c0bd1467fb881435375b2",
  "globalExitRoot": "0x8153fb885ba5ccef9063af371c0803318d56ba65192387f9c8a9aca8373809ff",
  "localExitRoot": "0xdcdcff63a1d2d64154e2f480d804131b2c399e04a850f70e36b48b39608a22c0",
  "mainnetExitRoot": "0x6ce23142c0a224657d8a53ce226308864c096d55694eca00bd9c3b3e472a3b42",
  "number": "0x1ff87",
  "rollupExitRoot": "0x1701a28ea10b5b1e7a62f60e857addc01653b5ccde773e77af1554805eda21da",
  "sendSequencesTxHash": "0x49018954cd5f94086b455917cb976f992cc8cda337672a82d058d0909d075db8",
  "stateRoot": "0xb2dbc1890279a290c244b86a24eaeef48044e05df7f66c0e858c24052042a856",
  "timestamp": "0x673596c5",
  "transactions": 73,
  "verifyBatchTxHash": "0xa1b73bc1e9f4d290ca29e5d0cce2cba4573fe109abeb48b53f5bfe1f17ab1f81"
}

JSON files saved at /var/folders/7m/3_x4ns7557x52hb6vncqkx8h0000gn/T/tmp.ycwQoTVmIz
Comparing cardona_130951_1.json and cardona_130951_2.json:
✅ No diff

Comparing cardona_130951_1.json and cardona_130951_3.json:
❌ Diff:
--- /dev/fd/63	2024-11-14 09:14:27
+++ /dev/fd/62	2024-11-14 09:14:27
@@ -1,5 +1,5 @@
 {
-  "accInputHash": "0xfd5141b2892e3b8ac99427a3fa89e940af87072c58e2deaf70c88b9086ccb7ce",
+  "accInputHash": "0x86c9ccbb52dc881fc344f36165972228958a33c2bbaa04a6dbbf71bc8bbfae76",
   "blocks": 574,
   "closed": true,
   "coinbase": "0x761d53b47334bee6612c0bd1467fb881435375b2",

Comparing cardona_130951_1.json and cardona_130951_4.json:
✅ No diff

Comparing cardona_130951_2.json and cardona_130951_3.json:
❌ Diff:
--- /dev/fd/63	2024-11-14 09:14:27
+++ /dev/fd/62	2024-11-14 09:14:27
@@ -1,5 +1,5 @@
 {
-  "accInputHash": "0xfd5141b2892e3b8ac99427a3fa89e940af87072c58e2deaf70c88b9086ccb7ce",
+  "accInputHash": "0x86c9ccbb52dc881fc344f36165972228958a33c2bbaa04a6dbbf71bc8bbfae76",
   "blocks": 574,
   "closed": true,
   "coinbase": "0x761d53b47334bee6612c0bd1467fb881435375b2",

Comparing cardona_130951_2.json and cardona_130951_4.json:
✅ No diff

Comparing cardona_130951_3.json and cardona_130951_4.json:
❌ Diff:
--- /dev/fd/63	2024-11-14 09:14:27
+++ /dev/fd/62	2024-11-14 09:14:27
@@ -1,5 +1,5 @@
 {
-  "accInputHash": "0x86c9ccbb52dc881fc344f36165972228958a33c2bbaa04a6dbbf71bc8bbfae76",
+  "accInputHash": "0xfd5141b2892e3b8ac99427a3fa89e940af87072c58e2deaf70c88b9086ccb7ce",
   "blocks": 574,
   "closed": true,
   "coinbase": "0x761d53b47334bee6612c0bd1467fb881435375b2",
```
</details>

**Comment by Sharonbc01** [comment]
Okay thanks @leovct. 

Lets leave this issue open to test again on Cardona when we update to v2.60.x in that environment then.

**Comment by leovct** [comment]
I don't see the error on Cardona anymore, it looks good to me!
