### ISSUE TITLE
[RPC] stop batch on sequencer doesn't close on the RPC side

### ISSUE THREAD

**Issue by hexoscott** [0xPolygon/cdk-erigon#1344]
When performing a network upgrade to a new fork the sequencer is set with a batch to halt at.  This process closes the batch as expected and from a sequencer perspective everything works OK.  On the RPC side the batch remains with `closed: false` status which will not allow the upgrade to happen, we need to address this and ensure the RPC node also closes the batch in the stream and reports `closed: true`.

**Comment by V-Staykov** [comment]
Half of the problem is already fixed - the datastream server on the rpc checks if we have received a batch end on the datastream from the sequencer and adds to its own if needed. The other half (returning closed: true for the batch) is addressed in this issue:https://github.com/0xPolygonHermez/cdk-erigon/issues/1329

**Comment by Sharonbc01** [comment]
I re-opened this issue and place the the v2.60 milestone as we were still seeing i6,  thread here https://0xpolygon.slack.com/archives/C06QFF1P8MV/p1730723199378129

**Comment by Sharonbc01** [comment]
@rafael-genes @xavier-romero  will validate this fix in Beta 6 Monday Nov 11 am European time.

**Comment by xavier-romero** [comment]
I can confirm the batch before the halting one is reported as closed now by RPC @Sharonbc01

**Comment by Sharonbc01** [comment]
Thanks @xavier-romero  will close this.
